controllers/UsersController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Users;
use app\models\UsersSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use \yii\web\Response;
use yii\helpers\Html;
use yii\web\UploadedFile;
use kartik\mpdf\Pdf;
use app\models\Settings;
use app\models\User;
use app\models\additional\Permissions;
use app\models\Questionary;
use app\models\Resume;
use app\models\Chat;
use app\modules\api\controllers\BotinfoController;

/**
 * UsersController implements the CRUD actions for Users model.
 */
class UsersController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'rules' => [
                   [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                    'bulkdelete' => ['post'],
                ],
            ],
        ];
    }

    public function actionDashboard()
    {
        return $this->render('dashboard', [
            'questionaryCount' => 0,
            'resumeCount' => 0,
            'resumeTodayCount' => 0,
            'sendCount' => 0,
        ]);  
    }

    /**
     * Lists all Users models.
     * @return mixed
     */
    public function actionIndex()
    {    
        $searchModel = new UsersSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->sort->defaultOrder = ['id' => SORT_DESC];

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Creates a new Users model.
     * For ajax request will return json object
     * and for non-ajax request if creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $request = Yii::$app->request;
        $model = new Users();  

        if($request->isAjax){
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            if($model->load($request->post()) && $model->save()){
                return [
                    'forceReload'=>'#crud-datatable-pjax',
                    'size' => 'normal',
                    'title'=> "Создать",
                    'content'=>'<span class="text-success">Успешно выпольнено</span>',
                    'footer'=> Html::button('Ок',['class'=>'btn btn-primary pull-left','data-dismiss'=>"modal"]).
                            Html::a('Создать ещё',['create'],['class'=>'btn btn-info','role'=>'modal-remote'])
        
                ];         
            }else{           
                return [
                    'title'=> "Создать",
                    'size' => 'large',
                    'content'=>$this->renderAjax('create', [
                        'model' => $model,
                    ]),
                    'footer'=> Html::button('Отмена',['class'=>'btn btn-primary pull-left','data-dismiss'=>"modal"]).
                                Html::button('Сохранить',['class'=>'btn btn-info','type'=>"submit"])
        
                ];         
            }
        }else{
            /*
            *   Process for non-ajax request
            */
            if ($model->load($request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            } else {
                return $this->render('create', [
                    'model' => $model,
                ]);
            }
        }
       
    }

    /**
     * Updates an existing Users model.
     * For ajax request will return json object
     * and for non-ajax request if update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $request = Yii::$app->request;
        $model = $this->findModel($id);       

        if($request->isAjax){
            Yii::$app->response->format = Response::FORMAT_JSON;

            if($model->load($request->post()) && $model->save()) {
              return ['forceClose'=>true,'forceReload'=>'#crud-datatable-pjax'];   
            }else{
                 return [
                    'title'=> $model->getPermission(),
                    'size' => 'large',
                    'content'=>$this->renderAjax('update', [
                        'model' => $model,
                    ]),
                    'footer'=> Html::button('Отмена',['class'=>'btn btn-primary pull-left','data-dismiss'=>"modal"]).
                                Html::button('Сохранить',['class'=>'btn btn-info','type'=>"submit"])
                ];        
            }
        }else{
            /*
            *   Process for non-ajax request
            */
            if ($model->load($request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            } else {
                return $this->render('update', [
                    'model' => $model,
                ]);
            }
        }
    }

    /**
     * Creates a new Users model.
     * For ajax request will return json object
     * and for non-ajax request if creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionAvatar()
    {
        $request = Yii::$app->request;
        $id = Yii::$app->user->identity->id;
        $model = Users::findOne(Yii::$app->user->identity->id);  

        if($request->isAjax){
            Yii::$app->response->format = Response::FORMAT_JSON;
            if($model->load($request->post()) && $model->validate()){

                $model->file = UploadedFile::getInstance($model, 'file');
                if(!empty($model->file)){
                    $model->file->saveAs('avatars/'.$id.'.'.$model->file->extension);
                    Yii::$app->db->createCommand()->update('users', ['foto' => $id.'.'.$model->file->extension], [ 'id' => $id ])->execute();
                }

                return [
                    'forceReload'=>'#profile-pjax',
                    'size' => 'normal',
                    'title'=> "Аватар",
                    'forceClose' => true,     
                ];         
            }else{           
                return [
                    'title'=> "Аватар",
                    'size' => 'small',
                    'content'=>$this->renderAjax('avatar', [
                        'model' => $model,
                    ]),
                    'footer'=> Html::button('Отмена',['class'=>'btn btn-primary pull-left','data-dismiss'=>"modal"]).
                                Html::button('Сохранить',['class'=>'btn btn-info','type'=>"submit"])
        
                ];         
            }
        }
       
    }

    public function actionChange($id)
    {
        $request = Yii::$app->request;
        $model = $this->findModel($id);       

        if($request->isAjax){
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            if($model->load($request->post()) && $model->save()){
                
                return [
                    'forceClose' => true,
                    'forceReload'=>'#profile-pjax',
                ];    
            }else{
                 return [
                    'title'=> "Изменить",
                    'size' => "large",
                    'content'=>$this->renderAjax('change', [
                        'model' => $model,
                    ]),
                    'footer'=> Html::button('Отмена',['class'=>'btn btn-primary pull-left','data-dismiss'=>"modal"]).
                                Html::button('Сохранить',['class'=>'btn btn-info','type'=>"submit"])
                ];        
            }
        }
        else{
            echo "ddd";
        }
    }

    public function actionProfile()
    {
        $request = Yii::$app->request;
        return $this->render('profile', [
        ]);        
    }

    /**
     * Delete an existing Users model.
     * For ajax request will return json object
     * and for non-ajax request if deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $request = Yii::$app->request;
        if($id != 1) $this->findModel($id)->delete();

        if($request->isAjax){
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ['forceClose'=>true,'forceReload'=>'#crud-datatable-pjax'];
        }else{
            return $this->redirect(['index']);
        }
    }

    /**
     * Delete multiple existing Vacancy model.
     * For ajax request will return json object
     * and for non-ajax request if deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionBulkDelete()
    {        
        $request = Yii::$app->request;
        $pks = explode(',', $request->post( 'pks' )); // Array or selected records primary keys
        foreach ( $pks as $pk ) {
            $model = $this->findModel($pk);
            if($pk != 1) $model->delete();
        }

        if($request->isAjax){
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ['forceClose'=>true,'forceReload'=>'#crud-datatable-pjax'];
        }else{
            /*

views/yii2-app/layouts/content.php
<?php
use yii\widgets\Breadcrumbs;
use app\widgets\Alert;

?>
<div class="content-wrapper">
    <!-- <section class="content-header">
        <?php /*if (isset($this->blocks['content-header'])) {*/ ?>
            <h1><?php /*$this->blocks['content-header']*/ ?></h1>
        <?php /*} else {*/ ?>
            <h1>
                <?php
                /*if ($this->title !== null) {
                    echo \yii\helpers\Html::encode($this->title);
                } else {
                    echo \yii\helpers\Inflector::camel2words(
                        \yii\helpers\Inflector::id2camel($this->context->module->id)
                    );
                    echo ($this->context->module->id !== \Yii::$app->id) ? '<small>Module</small>' : '';
                }*/ ?>
            </h1>
        <?php /*}*/ ?>

        <?php
        /*Breadcrumbs::widget(
            [
                'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
            ]
        )*/ ?>
    </section> -->

    <section class="content">
        <?= Alert::widget() ?>
        <?= $content ?>
    </section>
</div>
<footer class="main-footer">
    <div class="pull-right hidden-xs">
        <b>Version</b> 2.0
    </div>
    <strong>Copyright &copy; 2019 <a href="https://shop-crm.ru/portfolio?utm=teo_job">Разработчик TEO</a>.</strong> All rights
    reserved.
</footer>

<!-- Control Sidebar -->

<!-- Add the sidebar's background. This div must be placed
     immediately after the control sidebar -->

views/yii2-app/layouts/header-menu.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;

?>

<header >
    <div class="wrapper">
        <div class="logo">
            <a href="<?=Url::toRoute([Yii::$app->homeUrl])?>"><h2><?=Yii::$app->name?></h2></a>
        </div>
        <div class="hdr_menu">            
        </div>
        <div class="hdr_rght">            
        </div>
        <div class="hamburger">
            <span></span>
            <span></span>
            <span></span>
        </div>            
    </div>         
</header>

views/yii2-app/layouts/header.php
<?php
use yii\widgets\Breadcrumbs;
use app\widgets\Alert;
use yii\helpers\Html;
use app\models\Settings;
use app\models\Resume;
use yii\helpers\Url;
use app\models\Questionary;
use app\models\Chat;

/*if(Yii::$app->user->identity->type == 0) {
    $key_sms = Settings::findByKey('key_sms')->value;
    $inf = file_get_contents('https://smshub.org/stubs/handler_api.php?api_key='.$key_sms.'&action=getBalance');
    $balans = substr($inf,strpos($inf,':') + 1). ' SMS '.Yii::$app->user->identity->main_balance;
} else {
    $balans = Yii::$app->user->identity->main_balance;
}*/
?>


<!-- START X-NAVIGATION VERTICAL -->
<ul class="x-navigation x-navigation-horizontal x-navigation-panel">
    <!-- TOGGLE NAVIGATION -->
    <li class="xn-icon-button">
        <a href="#" onclick="$.post('/site/menu-position');" class="x-navigation-minimize"><span class="fa fa-dedent"></span></a>
    </li>


    <li class="xn-icon-button pull-right">
        <?= Html::a('<span class="fa fa-sign-out"></span>',['/site/logout'],['data-confirm'=> false, 'data-method'=>false,// for overide yii data api
            'data-request-method'=>'post',
            'data-toggle'=>'tooltip',]) ?>
    </li>

    <li class="pull-right">
        <?php //Html::a($balans. ' <i class="fa fa-rub"></i>', 'https://sms-activate.ru/', [ 'target' => '_blank',  'data' => ['pjax' => 0]])?>
    </li>
</ul>

<section class="breadcrumb push-down-0">

    <?php if (isset($this->blocks['content-header'])) { ?>
        <h1><?php $this->blocks['content-header'] ?></h1>
    <?php } else { ?>
    <?php } ?>

</section>

<div class="page-content-wrap">
    <br>
</div>

views/yii2-app/layouts/left.php
<?php
use yii\helpers\Html;
use yii\bootstrap\Modal;
use johnitvn\ajaxcrud\CrudAsset; 
use yii\helpers\Url;
use app\models\Users;
use yii\widgets\Pjax;

$path = 'http://' . $_SERVER['SERVER_NAME'].'/examples/images/users/avatar.jpg';
$pathInfo = Yii::$app->request->pathInfo;
$class = "";
if($pathInfo == 'name/index' || $pathInfo == 'surname/index' || $pathInfo == 'additional-information/index' || $pathInfo == 'user-agent/index') $class="active";

$classReport = "";
if($pathInfo == 'users/dashboard' || $pathInfo == 'logs/index' || $pathInfo == '') $classReport = "active";
?>
<?php 
        $session = Yii::$app->session;
        if($session['left'] == 'small') $left="x-navigation-minimized";
        else $left="x-navigation-custom";
    ?>
<!-- START PAGE SIDEBAR -->
            <div class="page-sidebar page-sidebar-fixed scroll">
                <!-- START X-NAVIGATION -->
                <ul class="x-navigation <?=$left?>">
                    <li class="xn-logo">
                        <a href="<?=Url::toRoute([Yii::$app->homeUrl])?>"><?=Yii::$app->name?></a>
                        <a href="#" class="x-navigation-control"></a>
                    </li>
                            <!-- <li <?php // ($pathInfo == 'users/dashboard' || $pathInfo == '' ? 'class="active"' : '')?> >
                                <?php // Html::a('<span class="fa fa-desktop"></span> Показатели', ['/users/dashboard'], []); ?>
                            </li> -->
                    
                     <li>
                        <?= Html::a('<span class="fa fa-list"></span> <span class="xn-text">Проекты</span>', ['/projects/index'], []); ?>
                    </li>
                    <li>
                        <?= Html::a('<span class="fa fa-cogs"></span> <span class="xn-text">Настройки</span>', ['/settings/index'], []); ?>
                    </li>
                    <li>
                        <?= Html::a('<span class="fa fa-users"></span> <span class="xn-text">Пользователи</span>', ['/users/index'], []); ?>
                    </li>
                    <!-- <li>
                        <?php // Html::a('<span class="glyphicon glyphicon-copyright-mark"></span> <span class="xn-text">Каналы</span>', ['/channels/index'], []); ?>
                    </li> -->
                    <!-- <li>
                        <?php // Html::a('<span class="fa fa-book"></span><span class="xn-text">Отчеты</span>', ['/reports/index'], []); ?>
                    </li> -->

                   <!--  <li class="xn-openable <?=$class?>"  >
                        <a href="#"><span class="fa fa-bar-chart-o"></span><span class="xn-text">Справочники</span></a>
                        <ul>
                        </ul>
                    </li> -->

                </ul>
                <!-- END X-NAVIGATION -->
            </div>
            <!-- END PAGE SIDEBAR -->

views/yii2-app/layouts/main-login.php
<?php
use backend\assets\AppAsset;
use yii\helpers\Html;
use app\widgets\Alert;

/* @var $this \yii\web\View */
/* @var $content string */

?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>" class="body-full-height" >
<head>
    <meta charset="<?= Yii::$app->charset ?>"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body class="login-container lightmode">

<?php $this->beginBody() ?>

	<?= Alert::widget() ?>
    <?= $content ?>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/yii2-app/layouts/main.php
<?php
use yii\helpers\Html;

$actionId = Yii::$app->controller->action->id;
if ($actionId  === 'login' || $actionId  === 'register') app\assets\RegisterAsset::register($this);
else app\assets\AppAsset::register($this);
//app\assets\AppAsset::register($this);

if (Yii::$app->controller->action->id === 'login' || Yii::$app->controller->action->id === 'register' || Yii::$app->controller->id === 'list' || Yii::$app->controller->id === 'setting') { 
    echo $this->render( 'main-login', ['content' => $content] );
} else {
    ?>
    <?php $this->beginPage() ?>
    <!DOCTYPE html>
    <html lang="<?= Yii::$app->language ?>">
    <head>
        <meta charset="<?= Yii::$app->charset ?>"/>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <?= Html::csrfMetaTags() ?>
        <title><?= Html::encode($this->title) ?></title>
        <?php $this->head() ?>
    </head>
    <?php 
        $session = Yii::$app->session;
        if($session['body'] == 'small') $body="page-navigation-toggled page-container-wide";
        else $body="";
    ?>
    <body class="">
    <?php $this->beginBody() ?>
        <div class="page-container <?=$body ?>">

            <?= $this->render( 'left.php', [] ) ?>
            <!-- PAGE CONTENT -->
            <div class="page-content">
                <?= Yii::$app->controller->id == 'default' ? $this->render( 'header-menu.php', [] ) : $this->render( 'header.php', [] ) ?>
                <?= $this->render( 'content.php', ['content' => $content, ] ) ?>
             </div>                       
            <!-- END PAGE CONTENT -->
        </div>
    <?php $this->endBody() ?>
    </body>
    </html>
    <?php $this->endPage() ?>
<?php } ?>

views/yii2-app/layouts/modal.php
<?php

use yii\helpers\Html;
use app\assets\AppAsset;

/* @var $this \yii\web\View */
/* @var $content string */

AppAsset::register($this);
?>

<?php $this->beginPage() ?>
<?= Html::csrfMetaTags() ?>
<?php $this->head() ?>
<?php $this->beginBody() ?>

<?= $content ?>

<?php $this->endBody() ?>
<?php $this->endPage() ?>

views/yii2-app/layouts/print.php
<?php
use yii\helpers\Html;

    ?>
    <?php $this->beginPage() ?>
    <!DOCTYPE html>
    <html lang="<?= Yii::$app->language ?>">
    <head>
        <meta charset="<?= Yii::$app->charset ?>"/>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title><?= Html::encode($this->title) ?></title>
        <?php $this->head() ?>
    </head>

    <body class="">
    <?php $this->beginBody() ?>
        <div class="page-container ">

            <!-- PAGE CONTENT -->
            <div class="page-content">
                <?= $content ?>
             </div>                       
            <!-- END PAGE CONTENT -->
        </div>
    <?php $this->endBody() ?>
    </body>
    </html>
    <?php $this->endPage() ?>